<?php
/**
 * @category Model
 * @package  ModernPdf\Model\Object
 * @author   Tristan Maindron <contact@owly-code.com>
 * @license  http://opensource.org/licenses/MIT MIT
 * @link     http://github.com/OwlyCode/ModernPdf
 */

namespace ModernPdf\Model\Object;

/**
 * Represents a graphic stream.
 */
class XmpMetadata extends Stream
{
    protected $graph;
    protected $resource;

    /**
     * @see Object::__construct()
     */
    public function __construct($objectNumber, $generationNumber = 0)
    {
        \EasyRdf_Namespace::set('dc', 'http://purl.org/dc/elements/1.1/');
        \EasyRdf_Namespace::set('xmp', 'http://ns.adobe.com/xap/1.0/');
        \EasyRdf_Namespace::set('pdfaid', 'http://www.aiim.org/pdfa/ns/id/');
        
        $this->graph = new \EasyRdf_Graph('http://www.w3.org/1999/02/22-rdf-syntax-ns#');
        $this->resource = $this->graph->resource();

        parent::__construct($objectNumber, $generationNumber);
    }

    public function addMetadata($name, $value, $type = null)
    {
        switch ($type) {
            case 'rdf:Alt': // The same as rdf:Seq
            case 'rdf:Seq':
                $seq = $this->graph->newBnode('rdf:Seq');
                foreach ($value as $item) {
                    $seq->append($item);
                    $this->resource->add($name, $seq);
                }
                break;
            default:
                $this->resource->set($name, $value);
        }
        
        $this->push($this->graph->serialise('rdfxml'));
    }

    public function push($data)
    {
        $this->data = array(
            "<?xpacket begin='' id='W5M0MpCehiHzreSzNTczkc9d'?>",
            preg_replace('/^.+\n/', '', $data), // removes the first line generated by EasyRDF (the xml declaration)
            "<?xpacket end='w'?>"
        );
        $this->baseType['Length'] = strlen($this->getRaw());
    }
}


/**
 * <dc:creator>Craig J. Hogan</dc:creator>
 * <dc:title>Cosmology: Ripples of early starlight</dc:title>
 * <dc:identifier>doi:10.1038/445037a</dc:identifier>
 * <dc:source>Nature 445, 37 (2007)</dc:source>
 * <dc:date>2007-01-04</dc:date>
 * <dc:format>application/pdf</dc:format>
 * <dc:publisher>Nature Publishing Group</dc:publisher>
 * <dc:language>en<dc:language>
 * <dc:rights>© 2007 Nature Publishing Group</dc:rights>
 */
